
version: '3.8'

services:
  # Frontend application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/
      - VITE_BASE_URL=/
    networks:
      - app-network
    volumes:
      - app-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Reverse proxy for security and SSL termination
  # Enable this when deploying to production with HTTPS
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=preview--idf-tasks-people-manager.lovable.app,idf-tasks-people-manager.lovable.app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
